name: CD

on:
  pull_request:
  push:
    # Branche na qual será feito o Build das versões
    branches:
      - main

jobs:
  # Configurações para o Build do Android
  build-android:
    name: Build Android
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.9"
      - run: flutter build appbundle

  # Configurações para o Build do IOS
  build-ios:
    name: Build IOS
    timeout-minutes: 30
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.9"
          architecture: x64
      - run: flutter build ios --release --no-codesign
